version: "3.8"

volumes:
  postgres-volume:

networks:
  postgres-network:
    driver: bridge

services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.10-bullseye
        USERNAME: vscode
        USER_UID: 1000
    init: true
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ..:/workspace:cached
    networks:
      - postgres-network
    command: sleep infinity
    user: vscode

  postgres:
    image: postgres:14.2-bullseye
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWD}@{POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postgres-network
