version: "3.8"

volumes:
  postgres-data:
  redis-cache:


services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.10-bullseye
        USERNAME: vscode
        USER_UID: 1000
    init: true
    ports:
      - 3109:3109
    env_file:
      - ../.env
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    user: vscode
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14.2-bullseye
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./dml.sql:/docker-entrypoint-initdb.d/add_data.sql

  redis:
    image: redis:6.2-bullseye
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass lk1x6E4wgDTjMye5EujsPxtbL5Y52VsM
    volumes:
      - redis-cache:/data
